package com.dotnomi.fabricdependencyinjection.kotlin.testclasses.multipleconstructors

import com.dotnomi.fabricdependencyinjection.annotation.ModMain

@ModMain
class MultipleConstructorsTestModMain 
