name: Publish To Github Packages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build and Release" ]
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    runs-on: [ ubuntu-latest ]

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        java: [ 21 ]

    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Elevate gradle wrapper
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Extract version from tag
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "Version: $VERSION"

      - name: Publish package
        run: ./gradlew -Pversion=${{ env.VERSION }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}